[package]
name = "hedtronix-crypto"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
ring.workspace = true
argon2.workspace = true
base64.workspace = true
serde.workspace = true
thiserror.workspace = true
anyhow.workspace = true
tracing.workspace = true
